### ISSUE TITLE
No module named 'mmwave' AND cannot import name 'dsp' from 'mmWave'

### ISSUE THREAD

**Issue by luluisthebest** [moodoki/radical_sdk#1]
Hi, Teck-Yian

I'd really like to use RaDICaL to do my research on 'Automotive radar signal interference mitigation' and there comes an issue when I run the codes. It shows there is no module named 'mmwave' as follows,

_File "D:\radical_sdk-master\radicalsdk\radar\v1.py", line 8, in <module>
    from mmwave import dsp
ModuleNotFoundError: No module named 'mmwave'_

Then, I installed 'mmWave-0.1.71', 

_Successfully installed mmWave-0.1.71_

However, there is no 'dsp' in '\_\_init\_\_.py' from module 'mmWave', as follows,

_from mmWave import dsp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dsp' from 'mmWave' (D:\Anaconda\lib\site-packages\mmWave\__init__.py)_

Therefore, I think that 'mmwave' module in your codes is different from 'mmWave' module which I installed. Can I ask where I can find 'mmwave' or was it written by you?

Thanks very much! Looking forward to your reply!

**Comment by moodoki** [comment]
The `mmwave` module that we are using is provided by [OpenRadar](https://github.com/PreSenseRadar/OpenRadar). It should be installed using `pip install openradar`. 

It should also be installed for you automatically if you used the installation method in the readme:
`python -m pip install git+https://github.com/moodoki/radical_sdk.git`
