### ISSUE TITLE
Inquiry Regarding Beamforming Angle Range for AWR1443 Raw Signal Processing

### ISSUE THREAD

**Issue by songhee-cho** [moodoki/radical_sdk#11]
Hi,
I noticed that in the processing pipeline for raw signal data from the AWR1443 sensor, a beamforming angle range of -90~90 degrees (180-degree) is being utilized. 
However, considering that the sensor boasts a 120-degree Field of View (FoV) and features 8 virtual antenna elements, I am curious about the rationale behind this specific angle range selection.

**Comment by moodoki** [comment]
120-degree field of view refers to the 3dB fall off angle based on the antenna design. I chose to beamform for +-90 degree as FFT beamforming naturally gives you +- 90deg. I've simply set the other beamforming methods to give me the same angles for convenience.

**Comment by songhee-cho** [comment]
Thank you for your helpful response.
I have another query: What would be the distinction between beamforming the data for ±60 degrees compared to for ±90 degrees for this dataset?

**Comment by moodoki** [comment]
Since the falloff beyond $\pm 60 ^\circ$ is $\geq 3 \text{dB}$, you can expect that signals there are very weak. Otherwise, there isn't much difference.
