### ISSUE TITLE
Doppler Deinterleaving

### ISSUE THREAD

**Issue by itberrios** [moodoki/radical_sdk#14]
Is the provided ADC data already deinterleaved for Time Division Multiplexing? The config files seem to always list twice as many chirps as the ADC data shows. For example, the indoor sample has 32 chirps in the ADC data, but the config file states that 64 chirps were used in what looks like an alternating manner for TDM.

The reason I am asking is because 'v1.py' always processes doppler with the default function parameters from mmwave's dsp implementation which will deinterleave the data. The mmwave implementation can be found [here](https://github.com/PreSenseRadar/OpenRadar/blob/master/mmwave/dsp/doppler_processing.py), using the default parameters in dsp.doppler_processing() reduces the number of range bins to 16 total, while it appears that there should be 32 after deinterleaving. 

Just a note, I haven't looked at *all* the data, just a few pieces so far.

**Comment by moodoki** [comment]
In our dataset, yes. The hardware documentation suggests so.

**Comment by itberrios** [comment]
Ok, thanks
