### ISSUE TITLE
Request for requirements.txt file

### ISSUE THREAD

**Issue by krastavcic** [moodoki/radical_sdk#9]
Hello,

I am currently working with the radical_sdk repository and I noticed that there isn't a `requirements.txt` file available. Currently there is a maintance in tensorflow_addons library and it seems I can't run code properly because of that.

I kindly request if you could consider adding a `requirements.txt` file to the repository. 

If you have specific instructions on how the project dependencies are managed or if there's an alternate way to obtain the package information, please feel free to provide guidance.

Thank you for your consideration. I look forward to your response.

**Comment by moodoki** [comment]
This repo is meant to be installed with `pip` or `setuptools`, the dependencies are in the `settings.ini`. https://github.com/moodoki/radical_sdk/blob/25e449df9341a8606b3efde3b765c1f2aeec19ea/settings.ini#L28
